# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "42e7052e2a04212ea5abc3e74d18ccaf"
name = "AI - Page Speed Optimizer"
application_url = "https://basketball-contents-wu-allowed.trycloudflare.com"
embedded = true
handle = "ai-speed-optimizer-01"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_themes"

[auth]
redirect_urls = ["https://basketball-contents-wu-allowed.trycloudflare.com/auth/callback", "https://basketball-contents-wu-allowed.trycloudflare.com/auth/shopify/callback", "https://basketball-contents-wu-allowed.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
